import os
import logging
import requests

TELEGRAM_API = "https://api.telegram.org"
logger = logging.getLogger(__name__)

def send_telegram_message(message: str) -> None:
    bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    if not bot_token:
        raise RuntimeError("TELEGRAM_BOT_TOKEN is not configured.")
    if not chat_id:
        raise RuntimeError("TELEGRAM_CHAT_ID is not configured.")

    url = f"{TELEGRAM_API}/bot{bot_token}/sendMessage"

    payload = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "Markdown" # Allows bolding for clean formatting
    }

    logger.info("Sending message to Telegram...")
    response = requests.post(url, json=payload, timeout=20)
    response.raise_for_status()

    data = response.json()
    if not data.get("ok"):
        raise RuntimeError(f"Telegram API error: {data}")
    
    logger.info("Message sent successfully.")

if __name__ == "__main__":
    # Read the message generated by eurusd_bot.py
    if not os.path.exists("message.txt"):
        logger.error("message.txt not found. Did the bot run successfully?")
    else:
        with open("message.txt", "r", encoding="utf-8") as f:
            message_content = f.read()
        send_telegram_message(message_content)